language: c

sudo: required

dist: trusty

branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO_NAME: c
    - DOXYFILE: $TRAVIS_BUILD_DIR/DOXYFILE
    - GH_REPO_REF: github.com/laurelmcintyre/c.git

addons:
  sonarcloud:
    organization: "laurelmcintyre-github"
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

before_install:
  - ccache -z

script:
  - ${CC} --coverage -c helloworld.c -o helloworld.o
  - ${CC} --coverage helloworld.o -o helloworld
  - ./helloworld
  - sonar-scanner
  
compiler:
  - gcc
  - clang

after_success:
  - ccache -s
  - if [ ${CC} = clang ]; then
      bash <(curl -s https://codecov.io/bash) -F ${CC} --gcov-exec "llvm-cov gcov";
    else
      bash <(curl -s https://codecov.io/bash) -F ${CC};
    fi
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
  - ./publish-doxygen
  
cache:
  ccache: true
  directories:
    - $HOME/.sonar
